// Code generated by "stringer -type=CreepType -trimprefix=Creep"; DO NOT EDIT.

package game

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[CreepNone-0]
	_ = x[CreepCheepy-1]
	_ = x[CreepImp-2]
	_ = x[CreepLion-3]
	_ = x[CreepFairy-4]
	_ = x[CreepClaws-5]
	_ = x[CreepMummy-6]
	_ = x[CreepKubus-7]
	_ = x[CreepDragon-8]
}

const _CreepType_name = "NoneCheepyImpLionFairyClawsMummyKubusDragon"

var _CreepType_index = [...]uint8{0, 4, 10, 13, 17, 22, 27, 32, 37, 43}

func (i CreepType) String() string {
	if i < 0 || i >= CreepType(len(_CreepType_index)-1) {
		return "CreepType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _CreepType_name[_CreepType_index[i]:_CreepType_index[i+1]]
}
