// Code generated by "stringer -type=CreepTrait -trimprefix=Trait"; DO NOT EDIT.

package game

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[TraitCoward-0]
	_ = x[TraitMagicImmunity-1]
	_ = x[TraitWeakToFire-2]
	_ = x[TraitSlow-3]
	_ = x[TraitRanged-4]
	_ = x[TraitBloodlust-5]
	_ = x[TraitIncrementalComplexity-6]
	_ = x[TraitMagicAura-7]
}

const _CreepTrait_name = "CowardMagicImmunityWeakToFireSlowRangedBloodlustIncrementalComplexityMagicAura"

var _CreepTrait_index = [...]uint8{0, 6, 19, 29, 33, 39, 48, 69, 78}

func (i CreepTrait) String() string {
	if i < 0 || i >= CreepTrait(len(_CreepTrait_index)-1) {
		return "CreepTrait(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _CreepTrait_name[_CreepTrait_index[i]:_CreepTrait_index[i+1]]
}
